---
title: "balanced RF"
author: "Yazhe"
date: "19/10/2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load("~/Desktop/Freddie_Mac_data/save_model/prepared_data.RData")
library(rpart)
library(randomForest)
library(parallel)
library(ROCR)
library(caret)
library(rpart.plot)
library(rpart)
library(gbm)
library(ROCR)
library(mlr)
library(unbalanced)
library(randomForest)
library(doParallel) 
library(ggplot2)
library(Rmisc)
library(smotefamily)
```

```{r}
auc_calucator = function(fitted.results, test_data_y) {
  pr <- prediction(fitted.results, test_data_y)
  prf <- ROCR::performance(pr, measure = "tpr", x.measure = "fpr")
  auc <- ROCR::performance(pr, measure = "auc")
  auc <- auc@y.values[[1]]
  return(c(auc,prf))
}
```

##balanced random rorest
```{r}
train$def_flag = as.factor(as.logical(train$def_flag))
test$def_flag = as.factor(as.logical(test$def_flag))
new_test = test[sample(1:nrow(test), size = nrow(test)/10),]
new_train = train[sample(1:nrow(train), size = nrow(train)/10),]
```

```{r}
boost_sample = function(data){
  boost_sample_index = sample(1:nrow(data), size = nrow(data), replace = TRUE)
  boost_sample = data[boost_sample_index,]
  return(boost_sample)
}
```

```{r}
single_balanced_rf_tree = function(data,mtry){
  data$def_flag = as.factor(as.logical(data$def_flag))
  minorityclass = data[data$def_flag == TRUE | data$def_flag == 1,]
  majorityclass = data[data$def_flag == FALSE | data$def_flag == 0,]
  boost_minority = boost_sample(minorityclass)
  boost_majority = boost_sample(majorityclass)
  dataset = rbind(boost_minority,boost_majority)
  single_tree = randomForest(def_flag~., data=dataset, 
                           sampsize=c(nrow(minorityclass), nrow(minorityclass)), 
                           strata=dataset$def_flag ,replace = FALSE, 
                           ntree = 1, mtry = mtry)
  return (single_tree)
}
```


```{r}
p = ncol(data) - 1
single_tree = single_balanced_rf_tree(new_train,sqrt(p))
tr = getTree(single_tree, 1, labelVar=TRUE);tr
```

```{r}
my_balanced_RF = function (data, ntree, mtry){
  no_cores <- detectCores() - 1
  cl <- makeCluster(no_cores, type="FORK") 
  clusterEvalQ(cl,library(randomForest))
  l= parSapply(cl, 1:ntree, function(i,...) {single_balanced_rf_tree(data,mtry)},simplify = FALSE)
  stopCluster(cl)
  
  return(l)
}
```

```{r}
temp = my_balanced_RF(data = new_train, ntree = 2, mtry = sqrt(p))
```

```{r}
my_predict = function(model, newdata){
  sapply(seq(1:length(model)), function(i) {
                             predict(model[[i]],newdata = newdata, type="response")},
         simplify = TRUE)
         
}
```

```{r}
my_prob_predict = function(model, newdata){
  predict_train = my_predict(model, newdata)
  pro_train = rep(0,nrow(predict_train))
  for (i in 1:nrow(predict_train)){
  pro_train[i] = sum(predict_train[i,] == TRUE)/length(predict_train[i,] == TRUE)
  }
  
  return(pro_train)
}
```

```{r}
pro_train = my_prob_predict(model = temp, newdata = new_train)
pro_test = my_prob_predict(model = temp, newdata = new_test)
```

```{r}
auc_calucator(pro_train, new_train$def_flag)[[1]]
auc_calucator(pro_test, new_test$def_flag)[[1]]
```

#tune ntree from 100 to 500
```{r}
auc=rep(0,5)
for(i in 1:5){
  temp = my_balanced_RF(data = new_train, ntree = i*100, mtry = sqrt(p))
  pro_test = my_prob_predict(model = temp, newdata = new_test)
  auc[i] = auc_calucator(pro_test, new_test$def_flag)[[1]]
  rm(temp)
}
cbind(ntree = c(1:5)*100, auc = auc)
```


##delete over lapping
```{r}
Y = new_train[,8]
Y = as.numeric(Y)
X = new_train[,-8]
Y[which(Y==1)] = 0
Y[which(Y==2)] = 1
a = ubTomek(X, Y, verbose = TRUE)
un_train_set = cbind(a[[1]],def_flag = a[[2]])


tt = BLSMOTE(un_train_set[,-30],un_train_set[,30],K=5,C=5,dupSize=0,method =c("type2"))$data
names(tt)[30] = "def_flag"
new_train = un_train_set
```

```{r}
tt$def_flag = as.character(tt$def_flag)
tt$def_flag[which(tt$def_flag == "0")] = FALSE
tt$def_flag[which(tt$def_flag == "1")] = TRUE
temp = my_balanced_RF(data = new_train, ntree = 100, mtry = sqrt(p))
```

```{r}
auc=rep(0,5)
for(i in 1:5){
  temp = my_balanced_RF(data = new_train, ntree = i*100, mtry = sqrt(p))
  pro_test = my_prob_predict(model = temp, newdata = new_test)
  auc[i] = auc_calucator(pro_test, new_test$def_flag)[[1]]
  rm(temp)
}
cbind(ntree = c(1:5)*100, auc = auc)
```