---
title: "smote BRT"
author: "Yazhe"
date: "23/10/2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
load("~/Desktop/Freddie_Mac_data/save_model/prepared_data.RData")
library(caret)
library(rpart.plot)
library(rpart)
library(gbm)
library(ROCR)
library(mlr)
library(unbalanced)
library(randomForest)
library(doParallel) 
library(ggplot2)
library(Rmisc) 
library(parallel)
library(smotefamily)
auc_calucator = function(fitted.results, test_data_y) {
  pr <- prediction(fitted.results, test_data_y)
  prf <- ROCR::performance(pr, measure = "tpr", x.measure = "fpr")
  auc <- ROCR::performance(pr, measure = "auc")
  auc <- auc@y.values[[1]]
  return(c(auc,prf))
}
```

```{r, warning=FALSE}
new_test = test[sample(1:nrow(test), size = nrow(test)/10),]
new_train = train[sample(1:nrow(train), size = nrow(train)/10),]

new_train$def_flag = as.factor(as.logical(new_train$def_flag))
new_test$def_flag = as.factor(as.logical(new_test$def_flag))
```

```{r, warning=FALSE}
Y = new_train[,8]
Y = as.numeric(Y)
X = new_train[,-8]
Y[which(Y==1)] = 0
Y[which(Y==2)] = 1
Y = as.factor(Y)
a = ubTomek(X, Y, verbose = TRUE)
un_train_set = cbind(a[[1]],def_flag = a[[2]])
```
#un train set is a traing set which delete overlap

```{r, warning=FALSE}
un_frac_BLSMOTE_sample = function (data, dupSize){
 a = BLSMOTE(data[,!(names(data) %in%   "def_flag")],data$def_flag,K=5,C=5,dupSize=dupSize,method=c("type1"))$data
  names(a)[30]="def_flag"
  a$def_flag = as.character(a$def_flag)
  a$def_flag[which(a$def_flag == 1)] = 'yes'
  a$def_flag[which(a$def_flag == 0)] = 'no'
  return(a)
}
```

```{r, warning=FALSE}
un_BLSMOTE_auc_frac = function(data,dupSize){
  un_train_set = un_frac_BLSMOTE_sample(data, dupSize)
  gbmGrid <- expand.grid(interaction.depth=(3:6), n.trees=(1:40)*100, shrinkage=.01)
  gbmGrid$n.minobsinnode = rep(10,nrow(gbmGrid))
  bootControl = trainControl(method='cv',classProbs = TRUE,number=3,summaryFunction =       twoClassSummary)
  gmbFit<- caret::train(def_flag~., data = un_train_set, 
                        method = "gbm", 
                        verbose = F, 
                        trControl = bootControl, 
                        bag.fraction=0.5,
                        metric="ROC",
                        tuneGrid=gbmGrid)
  predict=predict (gmbFit ,newdata = new_test, type='prob')
  temp = auc_calucator(predict[,2],new_test$def_flag)
  auc = temp[[1]]
  return(auc)
}
```

```{r, warning=FALSE, include=FALSE}
un_BLSMOTE_auc_frac(data = un_train_set, dupSize = 1)

no_cores <- detectCores() - 1
cl <- makeCluster(no_cores, type="FORK") 
clusterEvalQ(cl, library(caret))
clusterEvalQ(cl, library(rpart))
clusterEvalQ(cl, library(unbalanced))
clusterEvalQ(cl, library(randomForest))
clusterEvalQ(cl, library(ROCR))
clusterEvalQ(cl, library(gbm))
clusterEvalQ(cl, library(Rmisc))
clusterEvalQ(cl, library(rpart))
clusterEvalQ(cl, library(smotefamily))
```

```{r}
result = parLapply(cl, (1:3), function(x) {un_BLSMOTE_auc_frac(data = un_train_set, dupSize = x)})
result
stopCluster(cl)
```



```{r, warning=FALSE}
data_smote1 = un_frac_BLSMOTE_sample(un_train_set,1);table(data_smote1$def_flag)
data_smote2 = un_frac_BLSMOTE_sample(un_train_set,2);table(data_smote2$def_flag)
data_smote3 = un_frac_BLSMOTE_sample(un_train_set,3);table(data_smote3$def_flag)
  
  
un_frac_sample = function (data, frac){
  Y = data$def_flag
  X = data[,!(names(data)  %in%   "def_flag")]
  Y[which(Y=="no")] = 0
  Y[which(Y=="yes")] = 1
  under_sample = ubUnder(X,Y, perc = frac, method = "percPos")
  un_train_set = cbind(under_sample[[1]],def_flag = under_sample[[2]])
  un_train_set$def_flag = as.numeric(un_train_set$def_flag)
  un_train_set$def_flag[which(un_train_set$def_flag == 2)] = 'yes'
  un_train_set$def_flag[which(un_train_set$def_flag == 1)] = 'no'
  return(un_train_set)
}


un_auc_frac = function(data, frac){
   un_train_set = un_frac_sample(data, frac)
   gbmGrid <- expand.grid(interaction.depth=(3:6), n.trees=(1:40)*100, shrinkage=.01)
   gbmGrid$n.minobsinnode = rep(10,nrow(gbmGrid))
   bootControl = trainControl(method='cv',classProbs = TRUE,number=3,summaryFunction =       twoClassSummary)
   gmbFit<- caret::train(def_flag~., data = un_train_set, 
               method = "gbm", 
               verbose = F, 
               trControl = bootControl, 
               bag.fraction=0.5,
               metric="ROC",
               tuneGrid=gbmGrid)
   predict=predict (gmbFit ,newdata = new_test, type='prob')
   temp = auc_calucator(predict[,2],new_test$def_flag)
   auc = temp[[1]]
   return(auc)
}
```


```{r, warning=FALSE}
ten_time_auc=function(data , frac){
  frac = rep(frac,10)
  auc = lapply(frac, function(x) {un_auc_frac(data = data ,frac = x)})
  return(unlist(auc))
}

```

change to use parallel here

```{r, warning=FALSE, include=FALSE}
#ten_time_auc(data = data_smote1, 50)

no_cores <- detectCores() - 1
cl <- makeCluster(no_cores, type="FORK") 
clusterEvalQ(cl, library(caret))
clusterEvalQ(cl, library(rpart))
clusterEvalQ(cl, library(unbalanced))
clusterEvalQ(cl, library(randomForest))
clusterEvalQ(cl, library(ROCR))
clusterEvalQ(cl, library(gbm))
clusterEvalQ(cl, library(Rmisc))
clusterEvalQ(cl, library(rpart))
clusterEvalQ(cl, library(smotefamily))
```

```{r}
result1 = parLapply(cl, c(5,10,15,20,25,30), function(x) {ten_time_auc(data = data_smote1, x)})

stopCluster(cl)
result1
```

```{r, warning=FALSE, include=FALSE}

no_cores <- detectCores() - 1
cl <- makeCluster(no_cores, type="FORK") 
clusterEvalQ(cl, library(caret))
clusterEvalQ(cl, library(rpart))
clusterEvalQ(cl, library(unbalanced))
clusterEvalQ(cl, library(randomForest))
clusterEvalQ(cl, library(ROCR))
clusterEvalQ(cl, library(gbm))
clusterEvalQ(cl, library(Rmisc))
clusterEvalQ(cl, library(rpart))
clusterEvalQ(cl, library(smotefamily))
```

```{r}
result2 = parLapply(cl, c(5,10,15,20,25,30), function(x) {ten_time_auc(data = data_smote2, x)})

stopCluster(cl)
result2
```

```{r, warning=FALSE, include=FALSE}

no_cores <- detectCores() - 1
cl <- makeCluster(no_cores, type="FORK") 
clusterEvalQ(cl, library(caret))
clusterEvalQ(cl, library(rpart))
clusterEvalQ(cl, library(unbalanced))
clusterEvalQ(cl, library(randomForest))
clusterEvalQ(cl, library(ROCR))
clusterEvalQ(cl, library(gbm))
clusterEvalQ(cl, library(Rmisc))
clusterEvalQ(cl, library(rpart))
clusterEvalQ(cl, library(smotefamily))
```

```{r}
result3 = parLapply(cl, c(5,10,15,20,25,30), function(x) {ten_time_auc(data = data_smote3, x)})

stopCluster(cl)
result3
```