---
title: "compare"
author: "Yazhe"
date: "15/10/2016"
output: pdf_document
---

```{r}
load("~/Desktop/Freddie_Mac_data/save_model/RF_noun_auc.Rdata")
load("~/Desktop/Freddie_Mac_data/save_model/RF_auc.RData")
load("~/Desktop/Freddie_Mac_data/save_model/logistic_auc.RData")
load("~/Desktop/Freddie_Mac_data/save_model/BRT_auc.Rdata")
load("~/Desktop/Freddie_Mac_data/save_model/BRT_noun_result.Rdata")
```

```{r fig.width=8,fig.height=7}
library(ROCR)

pr <- prediction(logistic_auc$pred, logistic_auc$result )
pr2 <- prediction(RF_auc$predict, RF_auc$result)
pr3 <- prediction(RF_noun_auc$predict, RF_noun_auc$result)
pr4 <- prediction(BRT_auc$predict, BRT_auc$result)
pr5 <- prediction(BRT_noun_result$predict, BRT_noun_result$result)

prf <- ROCR::performance(pr, "tpr", "fpr" )
prf2 <- ROCR::performance(pr2, "tpr", "fpr")
prf3 <- ROCR::performance(pr3, "tpr", "fpr")
prf4 <- ROCR::performance(pr4, "tpr", "fpr")
prf5 <- ROCR::performance(pr5, "tpr", "fpr")

plot(prf, col=rainbow(10)[1])
plot(prf2, col = rainbow(10)[3], add = TRUE)
plot(prf3, col = rainbow(10)[4], add = TRUE)
plot(prf4, col = rainbow(10)[7], add = TRUE)
plot(prf5, col = rainbow(10)[9], add = TRUE)

legend("bottomright", inset=.05, 
  	c("logistic","RF+undersample",'RF',"BRT+undersample","BRT"), fill=rainbow(10)[c(1,3,5,7,9)],box.lty=0)
lines(x = c(0,1), y = c(0,1))
```