---
title: "parameter distance"
author: "Yazhe"
date: "22/10/2016"
output: pdf_document
---
```{r, include=FALSE}
load("~/Desktop/Freddie_Mac_data/save_model/logistic state 10.10.RData")
library(ROCR)
library(Deducer)
library(grid)
library(devtools)
library(car)
library(ggplot2)
library(plyr)
library(easyGgplot2)
library(glmnet)
library(maps)
library(choroplethr)
library(ggfortify)
```

```{r}
#'x' is the column of a data.frame that holds 2 digit state codes
stateFromLower <-function(x) {
  #read 52 state codes into local variable [includes DC (Washington D.C. and PR (Puerto Rico)]
  st.codes<-data.frame(
    state=as.factor(c("AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA",
                      "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME",
                      "MI", "MN", "MO", "MS",  "MT", "NC", "ND", "NE", "NH", "NJ", "NM",
                      "NV", "NY", "OH", "OK", "OR", "PA", "PR", "RI", "SC", "SD", "TN",
                      "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY")),
    full=as.factor(c("alaska","alabama","arkansas","arizona","california","colorado",
                     "connecticut","district of columbia","delaware","florida","georgia",
                     "hawaii","iowa","idaho","illinois","indiana","kansas","kentucky",
                     "louisiana","massachusetts","maryland","maine","michigan","minnesota",
                     "missouri","mississippi","montana","north carolina","north dakota",
                     "nebraska","new hampshire","new jersey","new mexico","nevada",
                     "new york","ohio","oklahoma","oregon","pennsylvania","puerto rico",
                     "rhode island","south carolina","south dakota","tennessee","texas",
                     "utah","virginia","vermont","washington","wisconsin",
                     "west virginia","wyoming"))
  )
  #create an nx1 data.frame of state codes from source column
  st.x<-data.frame(state=x)
  #match source codes with codes from 'st.codes' local variable and use to return the full state name
  refac.x<-st.codes$full[match(st.x$state,st.codes$state)]
  #return the full state names in the same order in which they appeared in the original source
  return(refac.x)
  
}
```

```{r}
coef = as.data.frame(matrix(0,ncol = length(state.cv.fit[[i]]$coefficients), nrow = 54))

for (i in 1:54){
  coef[i,] = state.cv.fit[[i]]$coefficients
}
row.names(coef) = names(out)
```

```{r fig.height=7, fig.width=7}
aa = as.matrix(dist(coef, method = "euclidean", diag = FALSE, p = 2))
fit <- cmdscale(aa, eig=TRUE, k=2)
x <- fit$points[,1]
y <- fit$points[,2]

autoplot(cmdscale(aa,eig=TRUE, k=2), shape = FALSE,label = TRUE,label.colour = 'blue', label.size = 2) + annotate("rect", xmin = 1000, xmax = 1200, ymin = 70, ymax = 130,
  alpha = .4)
```

```{r}
t = which(fit$points[,1]<1200 & fit$points[,1]>1000 & fit$points[,2]>70 & fit$points[,2]<130);names(t)
```

```{r, warning=FALSE,fig.height=7, fig.width=7}
coef_nna = coef[, colSums(is.na(coef)) == 0]
Cluster <- kmeans(coef_nna, 5)

gr = list()

for (i in 1:5){
  gr[[i]] = names(which(Cluster$cluster==i))
  gr[[i]] = as.data.frame(cbind( region = gr[[i]] ,value = rep(0.2*i,length(gr[[i]]))))
}


oo = rbind(gr[[1]],gr[[2]],gr[[3]],gr[[4]],gr[[5]])
oo$region = stateFromLower(oo$region)
oo$value = as.numeric(as.character(oo$value))
oo = oo[complete.cases(oo),]


state_choropleth(oo,num_colors = 5,legend = "group",title = "state cluster based on parameter distance")
```


```{r}
load("~/Desktop/Freddie_Mac_data/USMortgages2008_2009.rdata")
D_state = D1[,-c(1,3,6,5,17,20,26)]
D_state = D_state[complete.cases(D_state),]
state = D_state$property.state
```

```{r}
numerical = subset(D_state, select=c("score", "CLTV", "DTI", "UPB", "LTV",
                                        "OIR"))
```

```{r}
pca <- prcomp(numerical, center = TRUE, scale. = TRUE) 
plot(pca, type = "l")
```

```{r, warning=FALSE}
temp = pca$x
temp = cbind(temp[,(1:2)],state)
temp = as.data.frame(temp)
names(temp)
temp$PC1 = as.numeric(as.character(temp$PC1))
temp$PC2 = as.numeric(as.character(temp$PC2))

aggdata <-aggregate(temp, by=list(state), FUN=mean)
```

```{}
ggplot(aggdata, aes(x= PC1, y= PC2, colour="Group.1", label=Group.1))+
  geom_point() +geom_text(aes(label=Group.1),hjust=0, vjust=0)
```

```{r}
for (i in 1:5) {
  gr[[i]]$group = i
}
group = rbind(gr[[1]],gr[[2]],gr[[3]],gr[[4]],gr[[5]])

tt = merge(x = group, y = aggdata, by.x = "region", by.y = "Group.1")
tt$group = as.factor(tt$group)
ggplot(tt, aes(x= PC1, y= PC2, colour=group, label=group))+
  geom_point() +geom_text(aes(label=region),hjust=0, vjust=0)
```